INSERT INTO "Category" (id, name) VALUES
('1', 'Food'),
('2', 'Transport'),
('3', 'Entertainment'),
('4', 'Utilities'),
('5', 'Healthcare'),
('6', 'Education'),
('7', 'Shopping'),
('8', 'Travel'),
('9', 'Housing'),
('10', 'Insurance'),
('11', 'Savings'),
('12', 'Miscellaneous'),
('13', 'Grocery'),
('14', 'Beverage'),
('15', 'Office Supplies'),
('16', 'Personal Care'),
('17', 'Subscriptions'),
('18', 'Gifts'),
('19', 'Charity'),
('20', 'Taxes'),
('21', 'Maintenance'),
('22', 'Electronics');